"""Validation-only diagnostics for adaptive misreport gating signals."""

from __future__ import annotations

import csv
import math
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from dataclasses import asdict, dataclass, fields
from pathlib import Path
from typing import Iterable

from .belief import BeliefTracker, entropy
from .benchmark import _stable_seed
from .channel import AnswerChannel, ReportMode, answer_channel_without_misreport
from .estimation import DiseaseStateModel
from .gating import HeuristicMisreportGate
from .questioning import NumpyQuestionSelector
from .schema import UNKNOWN, ClinicalCase
from .simulator import PatientProfile, StructuredPatientSimulator


@dataclass(frozen=True)
class GateEvent:
    """One answer together with signals available before updating the belief."""

    seed: int
    case_id: str
    diagnosis: str
    noise_rate: float
    turn: int
    feature: str
    true_state: str
    reported_value: str
    certainty: str
    true_report_mode: str
    predictive_probability: float
    surprisal: float
    gate_probability: float
    top_probability: float
    belief_entropy: float
    correct_top_before_answer: int
    latent_misreport: int
    wrong_report: int
    harmful_misreport: int


@dataclass(frozen=True)
class GateDiagnosticSummary:
    """Discrimination and current-threshold metrics for one binary target."""

    noise_group: str
    target: str
    events: int
    positives: int
    prevalence: float
    surprisal_auroc: float | None
    surprisal_average_precision: float | None
    gate_auroc: float | None
    gate_average_precision: float | None
    activation_threshold: float
    activations: int
    activation_precision: float | None
    activation_recall: float | None
    activation_false_positive_rate: float | None


Runtime = tuple[NumpyQuestionSelector, AnswerChannel, HeuristicMisreportGate]
_PROCESS_CONTEXT: tuple[DiseaseStateModel, Runtime, int, int] | None = None


def collect_gate_events(
    model: DiseaseStateModel,
    cases: Iterable[ClinicalCase],
    *,
    noise_rates: tuple[float, ...] = (0.0, 0.1, 0.2, 0.3),
    max_questions: int = 15,
    seed: int = 2026,
    progress: bool = False,
    workers: int = 1,
    executor_type: str = "thread",
) -> list[GateEvent]:
    """Collect gate signals on trajectories generated by the no-misreport policy.

    The adaptive gate is scored but is not allowed to alter the trajectory.  This
    prevents the diagnostic labels from depending on the gate being evaluated.
    """

    case_list = list(cases)
    if not case_list:
        raise ValueError("gate analysis needs at least one case")
    if not noise_rates:
        raise ValueError("noise rates cannot be empty")
    if max_questions <= 0:
        raise ValueError("max_questions must be positive")
    if workers <= 0:
        raise ValueError("workers must be positive")
    if executor_type not in {"thread", "process"}:
        raise ValueError("executor_type must be 'thread' or 'process'")
    for case in case_list:
        if case.diagnosis not in model.diseases:
            raise ValueError(f"validation disease missing from model: {case.diagnosis}")

    runtime = _make_runtime(model)
    tasks = [
        (case, noise_rate)
        for noise_rate in noise_rates
        for case in case_list
    ]

    def evaluate(task: tuple[ClinicalCase, float]) -> list[GateEvent]:
        return _evaluate_case_noise(
            task,
            model=model,
            runtime=runtime,
            max_questions=max_questions,
            seed=seed,
        )

    if workers == 1:
        executor = None
        results = map(evaluate, tasks)
    elif executor_type == "process":
        executor = ProcessPoolExecutor(
            max_workers=workers,
            initializer=_initialize_process_worker,
            initargs=(model, max_questions, seed),
        )
        results = executor.map(
            _process_evaluate,
            tasks,
            chunksize=max(1, len(tasks) // (workers * 20)),
        )
    else:
        executor = ThreadPoolExecutor(max_workers=workers)
        results = executor.map(evaluate, tasks)

    events: list[GateEvent] = []
    try:
        progress_interval = max(1, len(tasks) // 20)
        for task_index, rows in enumerate(results, start=1):
            events.extend(rows)
            if progress and (task_index % progress_interval == 0 or task_index == len(tasks)):
                print(
                    f"completed {task_index}/{len(tasks)} gate-diagnostic case-noise tasks",
                    flush=True,
                )
    finally:
        if executor is not None:
            executor.shutdown()
    return events


def _make_runtime(model: DiseaseStateModel) -> Runtime:
    selector = NumpyQuestionSelector()
    channel = answer_channel_without_misreport()
    gate = HeuristicMisreportGate()
    selector._ensure_numpy_cache(BeliefTracker(model, channel))
    return selector, channel, gate


def _evaluate_case_noise(
    task: tuple[ClinicalCase, float],
    *,
    model: DiseaseStateModel,
    runtime: Runtime,
    max_questions: int,
    seed: int,
) -> list[GateEvent]:
    case, noise_rate = task
    selector, channel, gate = runtime
    patient = StructuredPatientSimulator(
        diagnosis=case.diagnosis,
        latent_states=case.states,
        model=model,
        profile=PatientProfile.from_noise_rate(noise_rate),
        seed=_stable_seed(seed, case.case_id, noise_rate),
    )
    tracker = BeliefTracker(model, channel)
    asked = set()
    for initial in case.initial_observations:
        tracker.update(initial)
        asked.add(initial.key)

    rows: list[GateEvent] = []
    for turn in range(1, max_questions + 1):
        ranking = selector.rank(tracker, excluded=asked)
        if not ranking:
            break
        key = ranking[0].key
        observation, true_mode = patient.answer(key)
        predictive_probability = gate.predictive_probability(tracker, observation)
        predictive_probability = min(max(predictive_probability, 1e-300), 1.0)
        gate_probability = gate.probability(tracker, observation)
        top_diagnosis = max(tracker.belief, key=tracker.belief.__getitem__)
        true_state = patient.latent_states.get(key, UNKNOWN)
        wrong_report = int(
            true_state != UNKNOWN
            and observation.value != UNKNOWN
            and observation.value != true_state
        )
        latent_misreport = int(true_mode == ReportMode.MISREPORTED)
        rows.append(
            GateEvent(
                seed=seed,
                case_id=case.case_id,
                diagnosis=case.diagnosis,
                noise_rate=noise_rate,
                turn=turn,
                feature=key.token,
                true_state=true_state,
                reported_value=observation.value,
                certainty=observation.certainty.value,
                true_report_mode=true_mode.value,
                predictive_probability=predictive_probability,
                surprisal=-math.log(predictive_probability),
                gate_probability=gate_probability,
                top_probability=tracker.belief[top_diagnosis],
                belief_entropy=entropy(tracker.belief),
                correct_top_before_answer=int(top_diagnosis == case.diagnosis),
                latent_misreport=latent_misreport,
                wrong_report=wrong_report,
                harmful_misreport=int(latent_misreport and wrong_report),
            )
        )
        tracker.update(observation)
        asked.add(key)
    return rows


def _initialize_process_worker(
    model: DiseaseStateModel,
    max_questions: int,
    seed: int,
) -> None:
    global _PROCESS_CONTEXT
    _PROCESS_CONTEXT = (model, _make_runtime(model), max_questions, seed)


def _process_evaluate(task: tuple[ClinicalCase, float]) -> list[GateEvent]:
    if _PROCESS_CONTEXT is None:
        raise RuntimeError("gate-analysis process worker was not initialized")
    model, runtime, max_questions, seed = _PROCESS_CONTEXT
    return _evaluate_case_noise(
        task,
        model=model,
        runtime=runtime,
        max_questions=max_questions,
        seed=seed,
    )


def summarize_gate_events(
    events: Iterable[GateEvent],
    *,
    activation_threshold: float = 0.01,
) -> list[GateDiagnosticSummary]:
    """Summarize signal discrimination by noise rate and over all events."""

    rows = list(events)
    if not rows:
        raise ValueError("cannot summarize empty gate events")
    if not 0 <= activation_threshold < 1:
        raise ValueError("activation_threshold must be in [0, 1)")
    groups: list[tuple[str, list[GateEvent]]] = [("all", rows)]
    for noise_rate in sorted({row.noise_rate for row in rows}):
        groups.append(
            (
                f"{noise_rate:.2f}",
                [row for row in rows if row.noise_rate == noise_rate],
            )
        )

    summaries: list[GateDiagnosticSummary] = []
    targets = ("latent_misreport", "wrong_report", "harmful_misreport")
    for noise_group, group in groups:
        for target in targets:
            labels = [int(getattr(row, target)) for row in group]
            surprisal_scores = [row.surprisal for row in group]
            gate_scores = [row.gate_probability for row in group]
            predictions = [score > activation_threshold for score in gate_scores]
            positives = sum(labels)
            true_positives = sum(
                label and prediction
                for label, prediction in zip(labels, predictions)
            )
            false_positives = sum(
                not label and prediction
                for label, prediction in zip(labels, predictions)
            )
            negatives = len(labels) - positives
            activations = sum(predictions)
            summaries.append(
                GateDiagnosticSummary(
                    noise_group=noise_group,
                    target=target,
                    events=len(group),
                    positives=positives,
                    prevalence=positives / len(group),
                    surprisal_auroc=_roc_auc(labels, surprisal_scores),
                    surprisal_average_precision=_average_precision(
                        labels, surprisal_scores
                    ),
                    gate_auroc=_roc_auc(labels, gate_scores),
                    gate_average_precision=_average_precision(labels, gate_scores),
                    activation_threshold=activation_threshold,
                    activations=activations,
                    activation_precision=(
                        true_positives / activations if activations else None
                    ),
                    activation_recall=(
                        true_positives / positives if positives else None
                    ),
                    activation_false_positive_rate=(
                        false_positives / negatives if negatives else None
                    ),
                )
            )
    return summaries


def _roc_auc(labels: list[int], scores: list[float]) -> float | None:
    positives = sum(labels)
    negatives = len(labels) - positives
    if not positives or not negatives:
        return None
    ordered = sorted(zip(scores, labels), key=lambda item: item[0])
    positive_rank_sum = 0.0
    index = 0
    while index < len(ordered):
        end = index + 1
        while end < len(ordered) and ordered[end][0] == ordered[index][0]:
            end += 1
        average_rank = ((index + 1) + end) / 2.0
        positive_rank_sum += average_rank * sum(
            label for _, label in ordered[index:end]
        )
        index = end
    return (
        positive_rank_sum - positives * (positives + 1) / 2.0
    ) / (positives * negatives)


def _average_precision(labels: list[int], scores: list[float]) -> float | None:
    positives = sum(labels)
    if not positives:
        return None
    ordered = sorted(zip(scores, labels), key=lambda item: item[0], reverse=True)
    true_positives = 0
    seen = 0
    average_precision = 0.0
    index = 0
    while index < len(ordered):
        end = index + 1
        while end < len(ordered) and ordered[end][0] == ordered[index][0]:
            end += 1
        group_positives = sum(label for _, label in ordered[index:end])
        true_positives += group_positives
        seen += end - index
        average_precision += (
            group_positives / positives
        ) * (true_positives / seen)
        index = end
    return average_precision


def save_gate_events_csv(events: Iterable[GateEvent], path: str | Path) -> None:
    _save_dataclasses_csv(events, GateEvent, path)


def save_gate_summaries_csv(
    summaries: Iterable[GateDiagnosticSummary], path: str | Path
) -> None:
    _save_dataclasses_csv(summaries, GateDiagnosticSummary, path)


def _save_dataclasses_csv(
    rows: Iterable[object], row_type: type, path: str | Path
) -> None:
    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [field.name for field in fields(row_type)]
    with output_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(asdict(row))
